services:
  - type: web
    name: hbmapp
    runtime: node
    plan: free
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm run migrate && pnpm run import-data && pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://postgres:Z7rqy4jq%2F%214@db.rutzddguyzpyxuphzxru.supabase.co:5432/postgres
    healthCheckPath: /health

